export const IS_ERROR = 'IS_ERROR';
export const IS_LOADING = 'IS_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';